version: '3.8'

services:
  db: # MySQL
    image: mysql:8.0
    restart: always
    container_name: haeil-mysql
    ports:
      - "43306:3306" # 외부 접속 포트
    environment:
      MYSQL_DATABASE: haeil
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASS}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - haeil-net

volumes:
  mysql_data:

networks:
  haeil-net: